### ISSUE TITLE
Potential improvments to repository

### ISSUE THREAD

**Issue by VATICAN-PSYCHO** [cff29546/pzmap2dzi#14]
Hey, i found this tool very helpful and it's amazing.
However, I'm not Windows user and this does not work out of the box.
The thing that need changing is abandoning backslashes (\\) in favor of slashes (/).
Since this (slashes) also works in Windows, it would be nice.

Another things are mods and textures.
Every of them follow some kind schema (that is not os-agnostic).

For example `textures` list from `map_data.yaml`:

```
<texture-entry-name>:
    texture_root: mod_root
    texture_path: |-
        <steam-id</mods/<mod-id>/media/texturepacks
    texture_file_patterns: ['.*[.]pack']
```

This could be replaced with:

```
<texture-entry-name>:
    steam_id: <steam-id>
    mod_id: <mod_id>
```
Why? Because every texture so far follow same schema. Field `texture_file_patterns` is same everywhere, so it be either removed (and hardcoded) or set as default to (better option). Same goes for `texture_root`. `texture_path` can be build from `steam_id` and `mod_id`. Same could be done for maps.

Better option would be separating mod maps (and textures) from config at all. Since map can (but not must) contain own textures, so they can be easily detected (simple by looking for `texturepacks` directory inside `media `. Dependencies should be defined inside `mod.info` file so there is no need for explicit defining them (it up to the mod publisher to provide working mod, not you as code maintainer). That way every map mod can be submitted to this repository.

**Comment by ethano8225** [comment]
You had the example:

> For example textures list from map_data.yaml:
> ...

Sure every mod is in mod_root, currently. But if you're developing a mod that isn't on the workshop, and you wanted to add that mod to the default map, you'd have to make a fake modID to throw into your workshop folder in order to load it (with how you set it up). So maybe texture_root can be set to mod_root by default, only changed if the user provides a specific path
(and actually, texture_file_patterns could be pre-set too) ie
```
<texture-entry-name>:
    #texture_root: mod_root          #implicit unless texture_root is intentionally set by user
    texture_path: |-
        <steam-id</mods/<mod-id>/media/texturepacks 
    #texture_file_patterns: ['.*[.]pack']           #implicit
```
Maybe that could be changed to this:
```
<texture-entry-name>:
    steam_id: <steam-id>
    mod_id: <mod_id>
    #texture_root: mod_root                   #implicit 
    #texture_file_patterns: ['.*[.]pack']     #implicit
```
Then again, I would argue this is just as complicated as simply copying the whole path to the texture.pack files.

If you are having issues with \ not being interpreted correctly, use find and replace to find "\" and replace with "/". Many if not all file editors support this (i think even notepad)

**Comment by cff29546** [comment]
Here are some thoughts after reading the comments:

1. replace backslash: I see no problem. (no code change needed)
2. default texture_file_patterns: I see no problem. (no code change needed)
    - current code already defaults to `['.*[.]pack']`. 
3. use steam-id, mod-id, and mod-name and follow the path template: redesign config parsing logic
    - use a default template, for example `'{steam-id}/mods/{mod-id}/media/maps/{map-name}'`
    - user can overwrite the default template or exact path by manual config
4. config files structure: redesign for easy mod map description
    - Spread configuration into multiple files
    - one configuration file describes a few maps and a few textures
    - unify the texture and map description: allow map or texture or both described in the same entry

A configuration section example:
```
<entry_name>:
    steam_id: 1234567
    mod_id: 12345
    map_name: Name    # has map named `Name`
    texture: true     # has textures
    
    #values with default
    #
    #texture_root: mod_root
    #texture_path_pattern: '{steam-id}/mods/{mod-id}/media/texturepacks'
    #texture_path: ''   # force override texture_path if needed. example: 'test/texturepacks'
    #texture_file_patterns: ['.*[.]pack']
    #texture_files: []   # select texture packs and ignore texture_file_patterns. example: ['a.pack', 'b.pack']
    #map_root: mod_root
    #map_path_pattern: '{steam-id}/mods/{mod-id}/maps/{map-name}'
    #map_path: '' # force override map_path if needed
    #    example: 'media\maps\Muldraugh, KY'
    #encoding: utf8
    #depend_textures: ['default']    # Auto include private texture if exist
    ...
```

**Comment by VATICAN-PSYCHO** [comment]
Thank you for your response. I'm making similar project to yours, but focuses on performance (and self-learning). There is a piece of code that handles dependencies, based on mod.info. You could implement this feature here.

**Comment by cff29546** [comment]
> Thank you for your response. I'm making similar project to yours, but focuses on performance (and self-learning). There is a piece of code that handles dependencies, based on mod.info. You could implement this feature here.

Not all mod have a well written mod.info. My solution is to retrieve the Steam workshop page and extract the dependencies using regex matching.

get_mod_dep.py:
```python
import requests
import re

URL_TEMPLATE = 'https://steamcommunity.com/sharedfiles/filedetails/?id={mod_id}'
TITLE_PATTERN = re.compile('<div class="workshopItemTitle">([^<>]*)</div>')
DEP_PATTERN = re.compile('<a href="([^"]*)"[^>]*>\\s*<div class="requiredItem">\\s*(.*?)\\s*</div>\\s*</a>', re.MULTILINE)

def get_info(mod_id):
    url = URL_TEMPLATE.format(mod_id=mod_id)
    rsp = requests.get(url)

    title = None
    match = TITLE_PATTERN.search(rsp.text)
    if match:
        title = match.group(1)

    depend = []
    for match in DEP_PATTERN.finditer(rsp.text):
        if match:
            dep_id = match.group(1).split('=')[-1]
            dep_name = match.group(2)
            depend.append((dep_id, dep_name))

    return title, depend


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='mod dep getter')
    parser.add_argument('ids', nargs=argparse.REMAINDER)
    args = parser.parse_args()

    for steam_id in args.ids:
        title, dep = get_info(steam_id)
        print(title, dep)
```


An output example: 
```
>get_mod_dep.py 2820363371 2915656059
Ashenwood [('2337452747', 'Daddy Dirkie dirks tiles'), ('2599752664', "Dylan's Tile Pack"), ('2384329562', "throttlekitty's tiles")]
Cedar Hill [('2844685624', "TryHonesty's Tiles"), ('2774834715', "ExtraNoise's Newburbs Tiles"), ('2337452747', 'Daddy Dirkie dirks tiles')]
```

**Comment by VATICAN-PSYCHO** [comment]
I thought the same about this issue, but if for example, said mod doesn't have defined dependencies properly in mod.info, then this will not auto load them. You can test this by by loading (in-game) map that requires some tiles and vice versa try to unload tile mod.

You can also skip dependency checking and load all mods that are map (they have maps subdir), textures (texturepacks) and mixed (both maps and texturepacks directory present).

**Comment by ethano8225** [comment]
> then this will not auto load them

this would be an interesting way to go about it, but after looking at like 120 map folders when I made the PZ_map_collection files (in examples), I'd say about 40 of the maps would load properly (after accounting for 2 different formats for mod.info) with the rest simply failing because they don't have any dependencies, hell some don't even have mod_id in them, some only have a description of the map, etc. 

What I do know, is maybe there could be a table made for texturepack ID's and it's corresponding mod_id so it can easily be added to the list of required texturepacks. (Essentially, deleting the need to manually add texture packs at all). I believe (could certainly be wrong here, a different type of data might need to be used) you could use a python dictionary to make each mod_id correspond to one steamID, then find the location of the steam_id (of the texturepack) inside of the dict, and return the name that corresponds to it. Heck, you could use binary search to reduce that load time if a dictionary would work.

The point of this would be to provide the correct texturepack ID's when loading the map, as "throttlekitty's tiles" is not valid in this case. I'm sure there's a script that could be written to get these easily, most if not all mods provide the steamID at the bottom of their description, typically in the form
```
Workshop ID: 2337452747
Mod ID: Diederiks Tile Palooza
```
I know for the texture packs I personally added to the PZ_map_collection map_data file, I only used mod_id's to name all of the texture packs, so for those texture packs, this would work great. Some of the older built-in ones would need to be slightly changed to match the mod ID's, but other than that, it'd work.



So basically, with all of these improvements implemented, this would remove the need to provide:
texture_root (default to mod_root), 
texture_file_patterns (technically already done in the code), 
texture_path IF a user provides mod_id and steam_id (else, resort to using texture_path given by a user), 
depend_textures (entirely, it would be parsed from the workshop' pages "required mods" list, defaults to "default" if not found), 
texture_path (if the user provided mod_id and steam_id) 
and map_root (defaults to mod_root if not provided)
This would leave the format looking like this:
```
    FortRedstone:
        map_path: |-
            1516836158\mods\FortRedstone\media\maps\FortRedstone
        texture_path: |-
            1516836158\mods\FortRedstone\media\texturepacks
```
or like this:
```
    FortRedstone:
        mod_id: "FortRedstone" 
        steam_id: 1516836158      
```
to be clear, the original format was this:
```
    FortRedstone:
        map_root: mod_root
        map_path: |-
            1516836158\mods\FortRedstone\media\maps\FortRedstone
        encoding: utf8
        depend_texutres:
            - default
        texture_root: mod_root
        texture_path: |-
            1516836158\mods\FortRedstone\media\texturepacks
        texture_file_patterns: ['.*[.]pack']
```
I'd say thats a pretty solid improvement, as long as both forms can be accepted.

**Comment by ethano8225** [comment]
Quick update: I added support to include some depend_textures when running collect_mod_map_data, although some steamID's will still throw an error (everything in PZ map mod works). here is the [collect_map_mod_data.py](https://pastebin.com/32h3gi91) and [get_mod_dep.py](https://pastebin.com/e6PpV7xH) if anyone wants to take a look at it, im sure it could be improved lol

**Comment by cff29546** [comment]
I have updated the configuration format recently. Here's an example:
```
LittleTownship:
  map_name: LittleTownship
  mod_name: LittleTownship
  steam_id: '2542249811'
```
All default values are defined in [default.txt](https://github.com/cff29546/pzmap2dzi/blob/main/conf/default.txt).
I have also improved the script for collecting descriptions, which can now reuse collected dependencies. For more details, please refer to [Map description generation](https://github.com/cff29546/pzmap2dzi/blob/main/docs/adding_mod_maps.md#map-description-generation).

**Comment by cff29546** [comment]
Closing this as the configuration refactor is done.
